# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 09:27
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.SlugField(max_length=30)),
            ],
            options={"abstract": False},
        )
    ]
