# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 09:27
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import markupfield.fields
import yamlfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("namespace", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Addon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.SlugField(max_length=30)),
                (
                    "description",
                    markupfield.fields.MarkupField(
                        help_text="in markdown", rendered_field=True
                    ),
                ),
                (
                    "description_markup_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                        ],
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                ("_description_rendered", models.TextField(editable=False)),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="namespace.Namespace",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="AddonVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="`1.0` or `master` or `1.2-beta`",
                        max_length=30,
                    ),
                ),
                ("yaml", yamlfield.fields.YAMLField()),
                (
                    "native_package",
                    models.CharField(
                        help_text="installation representation of the platform native package with additional information, e.g.: `django==2.0`",
                        max_length=255,
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="addon.Addon",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.SlugField(max_length=30)),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="addonversion",
            name="platforms",
            field=models.ManyToManyField(
                help_text="Platforms this tag of the addon supports",
                to="addon.Platform",
            ),
        ),
    ]
