# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 06:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("addon", "0001_initial")]

    operations = [
        migrations.RemoveField(
            model_name="addonversion", name="native_package"
        ),
        migrations.AlterField(
            model_name="addonversion",
            name="addon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addonversions",
                to="addon.Addon",
            ),
        ),
        migrations.AlterField(
            model_name="addonversion",
            name="identifier",
            field=models.CharField(
                help_text="`1.0` or `master` or `1.2-beta`", max_length=30
            ),
        ),
    ]
