# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("addon", "0002_auto_20190521_0634")]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="identifier",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="addonversion",
            name="identifier",
            field=models.CharField(
                help_text="`1.0` or `master` or `1.2-beta`", max_length=255
            ),
        ),
    ]
