# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("addon", "0003_auto_20190522_0947")]

    operations = [
        migrations.AlterField(
            model_name="addonversion", name="yaml", field=models.TextField()
        )
    ]
